# Server Port
server.port=${PORT:8080}

# MySQL Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update

# File Upload Limits (allow up to 2GB for movies)
spring.servlet.multipart.max-file-size=2000MB
spring.servlet.multipart.max-request-size=2000MB

# Disable H2 console in production
spring.h2.console.enabled=false
