# Server Port
server.port=${PORT:8080}

# Oracle SQL Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Hibernate Configuration
# 'update' is useful for initial deploy, switch to 'validate' later for safety
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

# File Upload Limits
spring.servlet.multipart.max-file-size=2000MB
spring.servlet.multipart.max-request-size=2000MB

# Disable H2 console in production
spring.h2.console.enabled=false
